hero:
  text:
    code: <span class='opacity-40'>We exist to be and make</span><span class='text-primary'> eternally joyful disciples</span><span class='opacity-40'> of Jesus Christ</span>
    lang: html
  bgImage: /src/assets/site/heroBg.webp
cta:
  text:
    code: 10 am Sundays | Click here for livestream
    lang: html
  link: http://youtube.com/channel/UC5HBSGOC-FxOa3-ERY5X6mw/live
