pageTitle: Church Leadership
pageDescription: |-
  > Pay careful attention to yourselves and to all the flock, in which the Holy Spirit has made you overseers, to care for the church of God, which he obtained with his own blood. - Acts 20:28

  We believe that the local church should be led by a plurality of qualified elders. Sojourners Church has three elders that provide theological direction and teaching to the body of believers that they will one day give an account for. All elders are equal in authority and have different gifts, experiences, and abilities.
sections:
  - name: Pastors
    description: Staff and lay pastors
    entries:
      - michael-scarn
      - dwight-schrute
      - jim-halpert
  - name: Deacons
    description: Full of faith and the Holy Spirit
    entries:
      - pam-halpert
      - andy-bernard
      - creed-braton
